jenkins_version: "2.528.3"
jenkins_http_port: 8080
jenkins_java_opts: "-Djenkins.install.runSetupWizard=false"
jenkins_admin_user: admin
jenkins_admin_password: admin
jenkins_plugins:
  - git
  - workflow-aggregator
  - pipeline-stage-view
  - credentials-binding
  - ssh-slaves
  - matrix-auth
  - email-ext
  - timestamper
  - workspace-cleanup

