GIT_REPO: https://github.com/varshatripathi289-svg/Batch-33-MG-.git
GIT_BRANCH: main
KEEP_APPROVAL_STAGE: true
SLACK_CHANNEL_NAME: build-status
ENVIRONMENT: prod
ACTION_MESSAGE: "Deploying Jenkins"
ANSIBLE:
  INVENTORY: inventory
  PLAYBOOK: site.yml
  SSH_CREDENTIAL_ID: ansible-ssh-key
